// Generated by scripts/fetch_images.js — reference photos from Wikimedia Commons.
// Each: { img, credit (author), license, page }. Attribution shown in the app.
const IMAGES = {
 "Quartz": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Quartz_Br%C3%A9sil.jpg/500px-Quartz_Br%C3%A9sil.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Quartz_Br%C3%A9sil.jpg"
 },
 "Feldspar (Orthoclase)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/OrthoclaseBresil.jpg/500px-OrthoclaseBresil.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:OrthoclaseBresil.jpg"
 },
 "Calcite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Calcite_%28Mexique%29_.jpg/500px-Calcite_%28Mexique%29_.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Géry PARENT",
  "page": "https://commons.wikimedia.org/wiki/File:Calcite_(Mexique)_.jpg"
 },
 "Dolomite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Dolomite-Magn%C3%A9site-_Navarre.jpg/500px-Dolomite-Magn%C3%A9site-_Navarre.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Dolomite-Magn%C3%A9site-_Navarre.jpg"
 },
 "Halite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/SaltCrystaUSGOV.jpg/500px-SaltCrystaUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:SaltCrystaUSGOV.jpg"
 },
 "Fluorite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Fluorine_MHNT.MIN.2010.16.1.jpg/500px-Fluorine_MHNT.MIN.2010.16.1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Fluorine_MHNT.MIN.2010.16.1.jpg"
 },
 "Apatite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Apatit_aus_Renfrew_in_Kanada.jpg/500px-Apatit_aus_Renfrew_in_Kanada.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Burkhard Mücke",
  "page": "https://commons.wikimedia.org/wiki/File:Apatit_aus_Renfrew_in_Kanada.jpg"
 },
 "Talc": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Ciudad_Talca_Chile_junto_al_Volcan_Descabezado.jpg/500px-Ciudad_Talca_Chile_junto_al_Volcan_Descabezado.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Almoritmoxis",
  "page": "https://commons.wikimedia.org/wiki/File:Ciudad_Talca_Chile_junto_al_Volcan_Descabezado.jpg"
 },
 "Muscovite Mica": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/6/69/Mineraly.sk_-_muskovit.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY 2.0",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Mineraly.sk_-_muskovit.jpg"
 },
 "Hematite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Hematite.jpg/500px-Hematite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "DanielCD~commonswiki",
  "page": "https://commons.wikimedia.org/wiki/File:Hematite.jpg"
 },
 "Pyrite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Pyrite_-_Huanzala_mine%2C_Huallanca%2C_Bolognesi%2C_Ancash%2C_Peru.jpg/500px-Pyrite_-_Huanzala_mine%2C_Huallanca%2C_Bolognesi%2C_Ancash%2C_Peru.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Pyrite_-_Huanzala_mine,_Huallanca,_Bolognesi,_Ancash,_Peru.jpg"
 },
 "Galena": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Galena_Illinois_skyline.JPG/500px-Galena_Illinois_skyline.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Attribution",
  "credit": "DR04 of English Wikipedia",
  "page": "https://commons.wikimedia.org/wiki/File:Galena_Illinois_skyline.JPG"
 },
 "Graphite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/f/f3/GraphiteUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:GraphiteUSGOV.jpg"
 },
 "Chalcopyrite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Chalkopyrite.jpg/500px-Chalkopyrite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 3.0",
  "credit": "VikSl Exhibit from my own collection ( V.Slyotov, http://mindraw.web.ru/ )",
  "page": "https://commons.wikimedia.org/wiki/File:Chalkopyrite.jpg"
 },
 "Sphalerite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Sphalerite_-_Iron_Cap_mine%2C_Graham%2C_Arizona%2C_USA.jpg/500px-Sphalerite_-_Iron_Cap_mine%2C_Graham%2C_Arizona%2C_USA.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Sphalerite_-_Iron_Cap_mine,_Graham,_Arizona,_USA.jpg"
 },
 "Corundum": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Corundum.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Corundum.jpg"
 },
 "Garnet": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/GarnetCrystalUSGOV.jpg/500px-GarnetCrystalUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Unknown authorUnknown author",
  "page": "https://commons.wikimedia.org/wiki/File:GarnetCrystalUSGOV.jpg"
 },
 "Olivine": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Peridot2.jpg/500px-Peridot2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "No machine-readable author provided. S kitahashi assumed (based on copyright claims).",
  "page": "https://commons.wikimedia.org/wiki/File:Peridot2.jpg"
 },
 "Hornblende (Amphibole)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Amphibole.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Amphibole.jpg"
 },
 "Malachite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Malachit%2C_Kupferspat.jpg/500px-Malachit%2C_Kupferspat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Burkhard Mücke",
  "page": "https://commons.wikimedia.org/wiki/File:Malachit,_Kupferspat.jpg"
 },
 "Azurite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Azurite_-_New_Nevada_Lode%2C_La_Sal%2C_Utah%2C_USA.jpg/500px-Azurite_-_New_Nevada_Lode%2C_La_Sal%2C_Utah%2C_USA.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Azurite_-_New_Nevada_Lode,_La_Sal,_Utah,_USA.jpg"
 },
 "Turquoise": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Turquoise-ELD.jpg/500px-Turquoise-ELD.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "ELD editors (Eugène Le Deley). Company disapeared in 1930 [2], did not specify name of the photograph [3].",
  "page": "https://commons.wikimedia.org/wiki/File:Turquoise-ELD.jpg"
 },
 "Kyanite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/KyaniteUSGOV.jpg/500px-KyaniteUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:KyaniteUSGOV.jpg"
 },
 "Barite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Bariumsulfatpulver.png/500px-Bariumsulfatpulver.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "de:Benutzer:the-viewer",
  "page": "https://commons.wikimedia.org/wiki/File:Bariumsulfatpulver.png"
 },
 "Sulfur": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Sulfur_-_El_Desierto_mine%2C_San_Pablo_de_Napa%2C_Daniel_Campos_Province%2C_Potos%C3%AD%2C_Bolivia.jpg/500px-Sulfur_-_El_Desierto_mine%2C_San_Pablo_de_Napa%2C_Daniel_Campos_Province%2C_Potos%C3%AD%2C_Bolivia.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Sulfur_-_El_Desierto_mine,_San_Pablo_de_Napa,_Daniel_Campos_Province,_Potos%C3%AD,_Bolivia.jpg"
 },
 "Limonite/Goethite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Goethit-1597.jpg/500px-Goethit-1597.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Raimond Spekking",
  "page": "https://commons.wikimedia.org/wiki/File:Goethit-1597.jpg"
 },
 "Rhodochrosite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Rhodocrosite_6%28P%C3%A9rou%29.jpg/500px-Rhodocrosite_6%28P%C3%A9rou%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Géry Parent",
  "page": "https://commons.wikimedia.org/wiki/File:Rhodocrosite_6(P%C3%A9rou).jpg"
 },
 "Tourmaline": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Reina_Gossett_ArtAndFeminism_2016_MoMA.tif/lossless-page1-250px-Reina_Gossett_ArtAndFeminism_2016_MoMA.tif.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Marily Konstantinopoulou",
  "page": "https://commons.wikimedia.org/wiki/File:Reina_Gossett_ArtAndFeminism_2016_MoMA.tif"
 },
 "Spinel": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Spinel2.jpg/500px-Spinel2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "No machine-readable author provided. S kitahashi assumed (based on copyright claims).",
  "page": "https://commons.wikimedia.org/wiki/File:Spinel2.jpg"
 },
 "Zircon": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Zircon_andrew_aversa.jpg/500px-Zircon_andrew_aversa.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "T3nsilino",
  "page": "https://commons.wikimedia.org/wiki/File:Zircon_andrew_aversa.jpg"
 },
 "Staurolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/8/87/Staurolite-37001.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Staurolite-37001.jpg"
 },
 "Andalusite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Andalusite_-_Malacheta%2C_Minas_Gerais%2C_Brazil.jpg/500px-Andalusite_-_Malacheta%2C_Minas_Gerais%2C_Brazil.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Andalusite_-_Malacheta,_Minas_Gerais,_Brazil.jpg"
 },
 "Sillimanite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/0/08/SillimaniteUSGS.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:SillimaniteUSGS.jpg"
 },
 "Epidote": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Epidote_-_Canta%2C_Lima%2C_Peru.jpg/500px-Epidote_-_Canta%2C_Lima%2C_Peru.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Epidote_-_Canta,_Lima,_Peru.jpg"
 },
 "Diopside": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Diopside_Aoste.jpg/500px-Diopside_Aoste.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Diopside_Aoste.jpg"
 },
 "Actinolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Actinolite_Portugal.jpg/500px-Actinolite_Portugal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Actinolite_Portugal.jpg"
 },
 "Tremolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Tremolite_Campolungo.jpg/500px-Tremolite_Campolungo.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Tremolite_Campolungo.jpg"
 },
 "Wollastonite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Wollastonite_madagascar.jpg/500px-Wollastonite_madagascar.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Wollastonite_madagascar.jpg"
 },
 "Rhodonite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/8224M-rhodonite3.jpg/500px-8224M-rhodonite3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "CarlesMillan",
  "page": "https://commons.wikimedia.org/wiki/File:8224M-rhodonite3.jpg"
 },
 "Lepidolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Lepidolita.jpeg/500px-Lepidolita.jpeg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 2.0 br",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Lepidolita.jpeg"
 },
 "Chlorite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Adularia-Chlorite-Group-260072.jpg/500px-Adularia-Chlorite-Group-260072.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Adularia-Chlorite-Group-260072.jpg"
 },
 "Kaolinite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Mus%C3%A9um_de_Nantes_-_178_-_Kaolinite_%28Nantes%2C_France%29.jpg/500px-Mus%C3%A9um_de_Nantes_-_178_-_Kaolinite_%28Nantes%2C_France%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Koreller",
  "page": "https://commons.wikimedia.org/wiki/File:Mus%C3%A9um_de_Nantes_-_178_-_Kaolinite_(Nantes,_France).jpg"
 },
 "Prehnite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Prehnite_-_Southbury%2C_Connecticut%2C_USA.jpg/500px-Prehnite_-_Southbury%2C_Connecticut%2C_USA.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Prehnite_-_Southbury,_Connecticut,_USA.jpg"
 },
 "Lazurite (Lapis)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Lazurite.jpg/500px-Lazurite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Lazurite.jpg"
 },
 "Sodalite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Sodalith_-_Rohstein.jpg/500px-Sodalith_-_Rohstein.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Ra'ike (see also: de:Benutzer:Ra'ike)",
  "page": "https://commons.wikimedia.org/wiki/File:Sodalith_-_Rohstein.jpg"
 },
 "Nepheline": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Nepheline-Schorlomite-250211.jpg/500px-Nepheline-Schorlomite-250211.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Nepheline-Schorlomite-250211.jpg"
 },
 "Leucite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/PseudoleucitaEZ.jpg/500px-PseudoleucitaEZ.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 2.5",
  "credit": "Eurico Zimbres (FGEL/UERJ)",
  "page": "https://commons.wikimedia.org/wiki/File:PseudoleucitaEZ.jpg"
 },
 "Scapolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Skapolit%2C1_Benono%2C_Madagaskar.jpg/500px-Skapolit%2C1_Benono%2C_Madagaskar.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "No machine-readable author provided. Kluka assumed (based on copyright claims).",
  "page": "https://commons.wikimedia.org/wiki/File:Skapolit,1_Benono,_Madagaskar.jpg"
 },
 "Titanite (Sphene)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Titanite_crystals_on_Amphibole_-_Ochtendung%2C_Eifel%2C_Germany.jpg/500px-Titanite_crystals_on_Amphibole_-_Ochtendung%2C_Eifel%2C_Germany.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0 nl",
  "credit": "Fred Kruijen",
  "page": "https://commons.wikimedia.org/wiki/File:Titanite_crystals_on_Amphibole_-_Ochtendung,_Eifel,_Germany.jpg"
 },
 "Chrysoberyl": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/5/54/Chrysoberyl.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Chrysoberyl.jpg"
 },
 "Peridot (Gem Olivine)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Gemperidot.JPG/500px-Gemperidot.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Michelle Jo",
  "page": "https://commons.wikimedia.org/wiki/File:Gemperidot.JPG"
 },
 "Jadeite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/b/b8/Ubehandlet_gr%C3%B8nn_jade.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Thomas Nordengen",
  "page": "https://commons.wikimedia.org/wiki/File:Ubehandlet_gr%C3%B8nn_jade.jpg"
 },
 "Chalcedony": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Mineraly.sk_-_chalcedon.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY 2.0",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Mineraly.sk_-_chalcedon.jpg"
 },
 "Aragonite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Aragonite_2_Enguidanos.jpg/500px-Aragonite_2_Enguidanos.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Aragonite_2_Enguidanos.jpg"
 },
 "Siderite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Eisenmeteorit_aus_Hammersley_Range_in_Australien.jpg/500px-Eisenmeteorit_aus_Hammersley_Range_in_Australien.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Burkhard Mücke",
  "page": "https://commons.wikimedia.org/wiki/File:Eisenmeteorit_aus_Hammersley_Range_in_Australien.jpg"
 },
 "Smithsonite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Smithsonite_-_USGS_Mineral_Specimens_016.jpg/500px-Smithsonite_-_USGS_Mineral_Specimens_016.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Bureau of Mines",
  "page": "https://commons.wikimedia.org/wiki/File:Smithsonite_-_USGS_Mineral_Specimens_016.jpg"
 },
 "Cerussite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Cerussite_-_Nakhlak_mine%2C_Anarak%2C_Esfahan%2C_Iran.jpg/500px-Cerussite_-_Nakhlak_mine%2C_Anarak%2C_Esfahan%2C_Iran.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Cerussite_-_Nakhlak_mine,_Anarak,_Esfahan,_Iran.jpg"
 },
 "Witherite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Witherite-4aa2b.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Witherite-4aa2b.jpg"
 },
 "Anhydrite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Anhydrite_Arnave.jpg/500px-Anhydrite_Arnave.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Anhydrite_Arnave.jpg"
 },
 "Phyllite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/f/fe/PhylliteUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:PhylliteUSGOV.jpg"
 },
 "Schist": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Schistosoma_mansoni2.jpg/500px-Schistosoma_mansoni2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "The original uploader was Waisberg at English Wikipedia.",
  "page": "https://commons.wikimedia.org/wiki/File:Schistosoma_mansoni2.jpg"
 },
 "Gneiss": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Gneiss.jpg/500px-Gneiss.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "No machine-readable author provided. Siim assumed (based on copyright claims).",
  "page": "https://commons.wikimedia.org/wiki/File:Gneiss.jpg"
 },
 "Migmatite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Migmatite_2005.jpg/500px-Migmatite_2005.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Siim Sepp",
  "page": "https://commons.wikimedia.org/wiki/File:Migmatite_2005.jpg"
 },
 "Amphibolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Les_Monts-Verts_-_G%C3%A9oscope_20200813-03_Amphibolite.jpg/500px-Les_Monts-Verts_-_G%C3%A9oscope_20200813-03_Amphibolite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Pymouss",
  "page": "https://commons.wikimedia.org/wiki/File:Les_Monts-Verts_-_G%C3%A9oscope_20200813-03_Amphibolite.jpg"
 },
 "Marble": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Cararra-Steinbruch_retouched.jpg/500px-Cararra-Steinbruch_retouched.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Reiner Flassig",
  "page": "https://commons.wikimedia.org/wiki/File:Cararra-Steinbruch_retouched.jpg"
 },
 "Quartzite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/b/be/Quartzite_2_jpg.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Quartzite_2_jpg.jpg"
 },
 "Hornfels": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Hornfels.jpg/500px-Hornfels.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "User Fed on ru.wikipedia",
  "page": "https://commons.wikimedia.org/wiki/File:Hornfels.jpg"
 },
 "Serpentinite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/6/67/Green_serpentinite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Mwojteck",
  "page": "https://commons.wikimedia.org/wiki/File:Green_serpentinite.jpg"
 },
 "Soapstone": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Mineraly.sk_-_mastenec.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY 2.0",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Mineraly.sk_-_mastenec.jpg"
 },
 "Cinnabar": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Cinnabar.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Cinnabar.jpg"
 },
 "Realgar": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Realgar-Calcite-37467.jpg/500px-Realgar-Calcite-37467.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Realgar-Calcite-37467.jpg"
 },
 "Stibnite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Antimonit_Quarz_aus_Japan.jpg/500px-Antimonit_Quarz_aus_Japan.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Burkhard Mücke",
  "page": "https://commons.wikimedia.org/wiki/File:Antimonit_Quarz_aus_Japan.jpg"
 },
 "Molybdenite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Molybdenite_quebec2.jpg/500px-Molybdenite_quebec2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Molybdenite_quebec2.jpg"
 },
 "Arsenopyrite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Arsenopyrite_Tomeik.jpg/500px-Arsenopyrite_Tomeik.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 4.0",
  "credit": "Henk Smeets – tomeikminerals.com",
  "page": "https://commons.wikimedia.org/wiki/File:Arsenopyrite_Tomeik.jpg"
 },
 "Marcasite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/MarcassiteII.jpg/500px-MarcassiteII.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:MarcassiteII.jpg"
 },
 "Pyrrhotite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Mus%C3%A9um_de_Nantes_-_023_-_Pyrrhotite_%28Russie%29.jpg/500px-Mus%C3%A9um_de_Nantes_-_023_-_Pyrrhotite_%28Russie%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Koreller",
  "page": "https://commons.wikimedia.org/wiki/File:Mus%C3%A9um_de_Nantes_-_023_-_Pyrrhotite_(Russie).jpg"
 },
 "Bornite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Bornite-105006.jpg/500px-Bornite-105006.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Leon Hupperichs",
  "page": "https://commons.wikimedia.org/wiki/File:Bornite-105006.jpg"
 },
 "Cuprite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Cuprite_Crystals.jpg/500px-Cuprite_Crystals.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 4.0",
  "credit": "Masha Milshina",
  "page": "https://commons.wikimedia.org/wiki/File:Cuprite_Crystals.jpg"
 },
 "Chromite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/4/42/ChromiteUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:ChromiteUSGOV.jpg"
 },
 "Ilmenite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Ilmenite-173863.jpg/500px-Ilmenite-173863.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Modris Baum",
  "page": "https://commons.wikimedia.org/wiki/File:Ilmenite-173863.jpg"
 },
 "Rutile": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Titanium%28IV%29_oxide.jpg/500px-Titanium%28IV%29_oxide.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "The original uploader was Walkerma at English Wikipedia.",
  "page": "https://commons.wikimedia.org/wiki/File:Titanium(IV)_oxide.jpg"
 },
 "Cassiterite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/2/2e/CassiteriteUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:CassiteriteUSGOV.jpg"
 },
 "Wolframite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Wolframiteportugal2.jpg/500px-Wolframiteportugal2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Wolframiteportugal2.jpg"
 },
 "Pyrolusite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Pyrolusite_botryoidal.jpg/500px-Pyrolusite_botryoidal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Aram Dulyan (User:Aramgutang)",
  "page": "https://commons.wikimedia.org/wiki/File:Pyrolusite_botryoidal.jpg"
 },
 "Psilomelane": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Mineraly.sk_-_psilomelan.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY 2.0",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Mineraly.sk_-_psilomelan.jpg"
 },
 "Uraninite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Pichblende.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 2.5",
  "credit": "Template:Farhan",
  "page": "https://commons.wikimedia.org/wiki/File:Pichblende.jpg"
 },
 "Chrysocolla": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Mineraly.sk_-_chryzokol.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY 2.0",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Mineraly.sk_-_chryzokol.jpg"
 },
 "Dioptase": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Dioptasecongo2.jpg/500px-Dioptasecongo2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Dioptasecongo2.jpg"
 },
 "Vanadinite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Vanadinite_-_ACF_mine%2C_Mibladen%2C_Morocco.jpg/500px-Vanadinite_-_ACF_mine%2C_Mibladen%2C_Morocco.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Vanadinite_-_ACF_mine,_Mibladen,_Morocco.jpg"
 },
 "Wulfenite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Wulfenite_-_Red_Cloud_mine%2C_La_Paz_Co.%2C_Arizona%2C_USA.jpg/500px-Wulfenite_-_Red_Cloud_mine%2C_La_Paz_Co.%2C_Arizona%2C_USA.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Wulfenite_-_Red_Cloud_mine,_La_Paz_Co.,_Arizona,_USA.jpg"
 },
 "Pyromorphite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Pyromorphiteussel1.jpg/500px-Pyromorphiteussel1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Pyromorphiteussel1.jpg"
 },
 "Scheelite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Scheelite_MHNT.MIN.2004.0.88_%28p%29.jpg/500px-Scheelite_MHNT.MIN.2004.0.88_%28p%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Scheelite_MHNT.MIN.2004.0.88_(p).jpg"
 },
 "Fluorapatite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Apatite_Canada.jpg/500px-Apatite_Canada.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Apatite_Canada.jpg"
 },
 "Autunite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Autunite_carri%C3%A8re_Les_Oudots.jpg/500px-Autunite_carri%C3%A8re_Les_Oudots.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Autunite_carri%C3%A8re_Les_Oudots.jpg"
 },
 "Datolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Datolite-1116-02f.jpg/500px-Datolite-1116-02f.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Datolite-1116-02f.jpg"
 },
 "Natrolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Natroliteinde1.jpg/500px-Natroliteinde1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Natroliteinde1.jpg"
 },
 "Stilbite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Stilbite-Ca-pb34a.jpg/500px-Stilbite-Ca-pb34a.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Stilbite-Ca-pb34a.jpg"
 },
 "Heulandite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Heulandite-Ca-240277.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Heulandite-Ca-240277.jpg"
 },
 "Analcime": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Analcime_-_Kahwan_Mountain%2C_Semnan%2C_Iran.jpg/500px-Analcime_-_Kahwan_Mountain%2C_Semnan%2C_Iran.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Analcime_-_Kahwan_Mountain,_Semnan,_Iran.jpg"
 },
 "Axinite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Axinite-Mn_-_Canta%2C_Lima%2C_Peru.jpg/500px-Axinite-Mn_-_Canta%2C_Lima%2C_Peru.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Axinite-Mn_-_Canta,_Lima,_Peru.jpg"
 },
 "Cordierite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Cordierite_Italie.jpg/500px-Cordierite_Italie.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Cordierite_Italie.jpg"
 },
 "Danburite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/DanburiteMexique.jpg/500px-DanburiteMexique.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:DanburiteMexique.jpg"
 },
 "Spodumene": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Spodumene.jpg/500px-Spodumene.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "No machine-readable author provided. Vzb83~commonswiki assumed (based on copyright claims).",
  "page": "https://commons.wikimedia.org/wiki/File:Spodumene.jpg"
 },
 "Amblygonite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Estonian_Museum_of_Natural_History_Specimen_No_202251_photo_%28g27_g27-601_1_jpg%29.jpg/500px-Estonian_Museum_of_Natural_History_Specimen_No_202251_photo_%28g27_g27-601_1_jpg%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Mai Seppel",
  "page": "https://commons.wikimedia.org/wiki/File:Estonian_Museum_of_Natural_History_Specimen_No_202251_photo_(g27_g27-601_1_jpg).jpg"
 },
 "Lazulite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Lazulite-tmix07-166a.jpg/500px-Lazulite-tmix07-166a.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Lazulite-tmix07-166a.jpg"
 },
 "Variscite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Variscite.jpg/500px-Variscite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Variscite.jpg"
 },
 "Colemanite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/ColemaniteUSGOV.jpg/500px-ColemaniteUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:ColemaniteUSGOV.jpg"
 },
 "Borax": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Tincalconite_and_Borax_-_Baker_mine%2C_US_Borax_Mine%2C_Kramer_Borate_deposit%2C_California%2C_USA.jpg/500px-Tincalconite_and_Borax_-_Baker_mine%2C_US_Borax_Mine%2C_Kramer_Borate_deposit%2C_California%2C_USA.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 3.0",
  "credit": "Rock Currier",
  "page": "https://commons.wikimedia.org/wiki/File:Tincalconite_and_Borax_-_Baker_mine,_US_Borax_Mine,_Kramer_Borate_deposit,_California,_USA.jpg"
 },
 "Ulexite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Ulexite-39574.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Ulexite-39574.jpg"
 },
 "Cryolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/816-_Ivigtut_-_cryolite.jpg/500px-816-_Ivigtut_-_cryolite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:816-_Ivigtut_-_cryolite.jpg"
 },
 "Anglesite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Angl%C3%A9site-touizit_Monocristal.jpg/500px-Angl%C3%A9site-touizit_Monocristal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Angl%C3%A9site-touizit_Monocristal.jpg"
 },
 "Crocoite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Croco%C3%AFte_Dundas2p.jpg/500px-Croco%C3%AFte_Dundas2p.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Croco%C3%AFte_Dundas2p.jpg"
 },
 "Erythrite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Erythritemaroc1.jpg/500px-Erythritemaroc1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Erythritemaroc1.jpg"
 },
 "Adamite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Adamitemexique1.jpg/500px-Adamitemexique1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Adamitemexique1.jpg"
 },
 "Brucite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Brucite-215491.jpg/500px-Brucite-215491.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Brucite-215491.jpg"
 },
 "Boehmite/Diaspore": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Mineraly.sk_-_diaspor.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY 2.0",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Mineraly.sk_-_diaspor.jpg"
 },
 "Chondrodite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/5/51/Chondrodite-mf30b.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Chondrodite-mf30b.jpg"
 },
 "Vesuvianite (Idocrase)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Vesuvianite-196065.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Vesuvianite-196065.jpg"
 },
 "Kernite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kernite_-_USGS_Mineral_Specimens_692.jpg/500px-Kernite_-_USGS_Mineral_Specimens_692.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Andrew Silver",
  "page": "https://commons.wikimedia.org/wiki/File:Kernite_-_USGS_Mineral_Specimens_692.jpg"
 },
 "Alunite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Mineraly.sk_-_alunit_m.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY 2.0",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Mineraly.sk_-_alunit_m.jpg"
 },
 "Jarosite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Jarosite-114913.jpg/500px-Jarosite-114913.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Christian Rewitzer",
  "page": "https://commons.wikimedia.org/wiki/File:Jarosite-114913.jpg"
 },
 "Tigereye (Quartz)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Tigers-Eye.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Mitchell Gore (Lestatdelc at en.wikipedia)",
  "page": "https://commons.wikimedia.org/wiki/File:Tigers-Eye.jpg"
 },
 "Amazonite (Microcline)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/9/96/Microcline-fel1c.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Microcline-fel1c.jpg"
 },
 "Labradorite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Labradorite_detail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Gregory Phillips",
  "page": "https://commons.wikimedia.org/wiki/File:Labradorite_detail.jpg"
 },
 "Moonstone (Feldspar)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Feldspar-Group-291254.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Feldspar-Group-291254.jpg"
 },
 "Sunstone (Feldspar)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Feldspar-Group-291254.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Feldspar-Group-291254.jpg"
 },
 "Microcline": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/9/96/Microcline-fel1c.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Microcline-fel1c.jpg"
 },
 "Sanidine": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Sanidine-477065.jpg/500px-Sanidine-477065.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Val Collins",
  "page": "https://commons.wikimedia.org/wiki/File:Sanidine-477065.jpg"
 },
 "Enstatite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Enstatite-USGS-BYU492.jpg/500px-Enstatite-USGS-BYU492.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Andrew Silver",
  "page": "https://commons.wikimedia.org/wiki/File:Enstatite-USGS-BYU492.jpg"
 },
 "Aegirine": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Aegirine-Orthoclase-114177.jpg/500px-Aegirine-Orthoclase-114177.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Aegirine-Orthoclase-114177.jpg"
 },
 "Glaucophane": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Glaucophane_bleu_de_Groix.jpg/500px-Glaucophane_bleu_de_Groix.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Glaucophane_bleu_de_Groix.jpg"
 },
 "Riebeckite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/b/b5/Riebeckite-210685.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Riebeckite-210685.jpg"
 },
 "Grossular Garnet": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Grossular-57594.jpg/500px-Grossular-57594.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Grossular-57594.jpg"
 },
 "Chabazite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Chabazite_Tch%C3%A9quie.jpg/500px-Chabazite_Tch%C3%A9quie.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Chabazite_Tch%C3%A9quie.jpg"
 },
 "Laumontite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Prehnite-Laumontite-132299.jpg/500px-Prehnite-Laumontite-132299.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Prehnite-Laumontite-132299.jpg"
 },
 "Apophyllite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Apophyllite-54502.jpg/500px-Apophyllite-54502.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Apophyllite-54502.jpg"
 },
 "Pectolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Pectolite-118245.jpg/500px-Pectolite-118245.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Pectolite-118245.jpg"
 },
 "Charoite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Charoite_MFrey.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "derivative work: MichaelFrey (talk)\nCzaroit_płytka,_Rosja.jpg: Kluka",
  "page": "https://commons.wikimedia.org/wiki/File:Charoite_MFrey.jpg"
 },
 "Benitoite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Benitoite_HD.jpg/500px-Benitoite_HD.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Benitoite_HD.jpg"
 },
 "Hemimorphite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Hemimorphite_-_Mapimi%2C_Durango%2C_Mexico.jpg/500px-Hemimorphite_-_Mapimi%2C_Durango%2C_Mexico.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Hemimorphite_-_Mapimi,_Durango,_Mexico.jpg"
 },
 "Willemite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Willemite-130544.jpg/500px-Willemite-130544.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Christian Rewitzer",
  "page": "https://commons.wikimedia.org/wiki/File:Willemite-130544.jpg"
 },
 "Franklinite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Franklinit_mit_Zinkit_-_Franklin%2C_New_Jersey%2C_USA.jpg/500px-Franklinit_mit_Zinkit_-_Franklin%2C_New_Jersey%2C_USA.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Ra'ike (see also: de:Benutzer:Ra'ike)",
  "page": "https://commons.wikimedia.org/wiki/File:Franklinit_mit_Zinkit_-_Franklin,_New_Jersey,_USA.jpg"
 },
 "Descloizite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Descloizit_-_Mineralogisches_Museum_Bonn_%287288%29.jpg/500px-Descloizit_-_Mineralogisches_Museum_Bonn_%287288%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Raimond Spekking",
  "page": "https://commons.wikimedia.org/wiki/File:Descloizit_-_Mineralogisches_Museum_Bonn_(7288).jpg"
 },
 "Granite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Calangianus%2C_cava_di_granito_dismessa_%2802%29.jpg/500px-Calangianus%2C_cava_di_granito_dismessa_%2802%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Gianni Careddu",
  "page": "https://commons.wikimedia.org/wiki/File:Calangianus,_cava_di_granito_dismessa_(02).jpg"
 },
 "Diorite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Diorite.jpg/500px-Diorite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Siim Sepp (talk · contribs)",
  "page": "https://commons.wikimedia.org/wiki/File:Diorite.jpg"
 },
 "Gabbro": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/GabbroRockCreek1.jpg/500px-GabbroRockCreek1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Wilson44691 (Mark A. Wilson at the Wayback Machine, Department of Geology, The College of Wooster).",
  "page": "https://commons.wikimedia.org/wiki/File:GabbroRockCreek1.jpg"
 },
 "Peridotite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/3/3e/PeridotiteUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:PeridotiteUSGOV.jpg"
 },
 "Pegmatite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Alkaline_pegmatite.jpg/500px-Alkaline_pegmatite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 2.5",
  "credit": "No machine-readable author provided. Zimbres assumed (based on copyright claims).",
  "page": "https://commons.wikimedia.org/wiki/File:Alkaline_pegmatite.jpg"
 },
 "Rhyolite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Feinporphyr_alteriert_OED-2_2.jpg/500px-Feinporphyr_alteriert_OED-2_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Christian b219",
  "page": "https://commons.wikimedia.org/wiki/File:Feinporphyr_alteriert_OED-2_2.jpg"
 },
 "Andesite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Amygdaloidal_andesite.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Photographer: Siim Sepp, 2005",
  "page": "https://commons.wikimedia.org/wiki/File:Amygdaloidal_andesite.jpg"
 },
 "Basalt": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Basaltfels_aus_Popocatepetl%2C_Mexico.jpg/500px-Basaltfels_aus_Popocatepetl%2C_Mexico.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Burkhard Mücke",
  "page": "https://commons.wikimedia.org/wiki/File:Basaltfels_aus_Popocatepetl,_Mexico.jpg"
 },
 "Obsidian": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Obsidian_desktop_demo_workflow.jpg/500px-Obsidian_desktop_demo_workflow.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Langstonzac25",
  "page": "https://commons.wikimedia.org/wiki/File:Obsidian_desktop_demo_workflow.jpg"
 },
 "Pumice": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Bims-kos_hg.jpg/500px-Bims-kos_hg.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 2.5",
  "credit": "Hannes Grobe 07:59, 27 October 2007 (UTC)",
  "page": "https://commons.wikimedia.org/wiki/File:Bims-kos_hg.jpg"
 },
 "Scoria": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Scoria_Macro_Digon3.jpg/500px-Scoria_Macro_Digon3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "“Jonathan Zander (Digon3)\"",
  "page": "https://commons.wikimedia.org/wiki/File:Scoria_Macro_Digon3.jpg"
 },
 "Porphyry": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/S%C3%A4rna-Porphyr_P1000115.JPG/500px-S%C3%A4rna-Porphyr_P1000115.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 2.5",
  "credit": "Gunnar Ries Amphibol",
  "page": "https://commons.wikimedia.org/wiki/File:S%C3%A4rna-Porphyr_P1000115.JPG"
 },
 "Sandstone": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/SmallCrater06_ST_08.JPG/500px-SmallCrater06_ST_08.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Attribution",
  "credit": "This file is a work by Ester Inbar (user:ST or he:user:ST).\nMore of my work can be found in Category:Files by User:ST.\n\nIf you use my work outside Wikimedia I would appreciate being notified and referred to site where used here.",
  "page": "https://commons.wikimedia.org/wiki/File:SmallCrater06_ST_08.JPG"
 },
 "Siltstone": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/4/42/SiltstoneUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:SiltstoneUSGOV.jpg"
 },
 "Limestone": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Limestone_Formation_In_Waitomo.jpg/500px-Limestone_Formation_In_Waitomo.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Ingolfson",
  "page": "https://commons.wikimedia.org/wiki/File:Limestone_Formation_In_Waitomo.jpg"
 },
 "Dolostone": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Dolomite_Morocco.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "The original uploader was Dlloyd at English Wikipedia.",
  "page": "https://commons.wikimedia.org/wiki/File:Dolomite_Morocco.jpg"
 },
 "Coal": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Coal_%28Anthracite%29.JPG/500px-Coal_%28Anthracite%29.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 4.0",
  "credit": "Amcyrus2012",
  "page": "https://commons.wikimedia.org/wiki/File:Coal_(Anthracite).JPG"
 },
 "Chert / Flint": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Chertrsey_Road2.jpg/500px-Chertrsey_Road2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Christianmesmar",
  "page": "https://commons.wikimedia.org/wiki/File:Chertrsey_Road2.jpg"
 },
 "Rock Salt": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/SaltCrystaUSGOV.jpg/500px-SaltCrystaUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:SaltCrystaUSGOV.jpg"
 },
 "Rock Gypsum": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Gypsum_%2812249949575%29.jpg/500px-Gypsum_%2812249949575%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 2.0",
  "credit": "James Petts from London, England",
  "page": "https://commons.wikimedia.org/wiki/File:Gypsum_(12249949575).jpg"
 },
 "Plagioclase Feldspar": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Plagioklas1.jpg/500px-Plagioklas1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Chmee2",
  "page": "https://commons.wikimedia.org/wiki/File:Plagioklas1.jpg"
 },
 "Gypsum": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Gypse_Caresse.jpg/500px-Gypse_Caresse.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Didier Descouens",
  "page": "https://commons.wikimedia.org/wiki/File:Gypse_Caresse.jpg"
 },
 "Magnetite": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Magnetite-118736.jpg/500px-Magnetite-118736.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Magnetite-118736.jpg"
 },
 "Topaz": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Topaze%2C_quartz_fum%C3%A9_1.jpg/500px-Topaze%2C_quartz_fum%C3%A9_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Parent Géry",
  "page": "https://commons.wikimedia.org/wiki/File:Topaze,_quartz_fum%C3%A9_1.jpg"
 },
 "Diamond": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Rough_Diamond.jpg/500px-Rough_Diamond.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC0",
  "credit": "DGPC/ADF Luísa Oliveira",
  "page": "https://commons.wikimedia.org/wiki/File:Rough_Diamond.jpg"
 },
 "Beryl": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Beryl09.jpg/500px-Beryl09.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "Public domain",
  "credit": "Reno Chris at English Wikipedia",
  "page": "https://commons.wikimedia.org/wiki/File:Beryl09.jpg"
 },
 "Nephrite (Jade)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/0/00/Jadestein.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Wikimedia Commons",
  "page": "https://commons.wikimedia.org/wiki/File:Jadestein.jpg"
 },
 "Opal": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Opal-53714.jpg/500px-Opal-53714.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Opal-53714.jpg"
 },
 "Orpiment": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Orpiment-148270.jpg/500px-Orpiment-148270.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Orpiment-148270.jpg"
 },
 "Iolite (Cordierite gem)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Cordierite-den07-06aa.jpg/500px-Cordierite-den07-06aa.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Cordierite-den07-06aa.jpg"
 },
 "Tuff": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Guadalupe_Tuff.jpg/500px-Guadalupe_Tuff.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivan Fernanadez 1011",
  "page": "https://commons.wikimedia.org/wiki/File:Guadalupe_Tuff.jpg"
 },
 "Breccia": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Basalt_breccia.jpg/500px-Basalt_breccia.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "No machine-readable author provided. Siim assumed (based on copyright claims).",
  "page": "https://commons.wikimedia.org/wiki/File:Basalt_breccia.jpg"
 },
 "Shale": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Shale_formation%2C_Marble_Canyon%2C_Kootenay_National_Park%2C_British_Columbia%2C_2025-07-11.jpg/500px-Shale_formation%2C_Marble_Canyon%2C_Kootenay_National_Park%2C_British_Columbia%2C_2025-07-11.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Chris Woodrich",
  "page": "https://commons.wikimedia.org/wiki/File:Shale_formation,_Marble_Canyon,_Kootenay_National_Park,_British_Columbia,_2025-07-11.jpg"
 },
 "Chalk": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Seven_Sisters_3.jpg/500px-Seven_Sisters_3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "kallerna",
  "page": "https://commons.wikimedia.org/wiki/File:Seven_Sisters_3.jpg"
 },
 "Slate": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Slate_%28Knife_Lake_Formation%2C_metamorphism_at_2.7_Ga%2C_Neoarchean%3B_Rt._135_roadcut%2C_Gilbert%2C_Minnesota%2C_USA%29_3_%2823140002749%29.jpg/500px-Slate_%28Knife_Lake_Formation%2C_metamorphism_at_2.7_Ga%2C_Neoarchean%3B_Rt._135_roadcut%2C_Gilbert%2C_Minnesota%2C_USA%29_3_%2823140002749%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 2.0",
  "credit": "James St. John",
  "page": "https://commons.wikimedia.org/wiki/File:Slate_(Knife_Lake_Formation,_metamorphism_at_2.7_Ga,_Neoarchean;_Rt._135_roadcut,_Gilbert,_Minnesota,_USA)_3_(23140002749).jpg"
 },
 "Biotite Mica": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Biotite_aggregate_-_Ochtendung%2C_Eifel%2C_Germany.jpg/500px-Biotite_aggregate_-_Ochtendung%2C_Eifel%2C_Germany.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0 nl",
  "credit": "Fred Kruijen",
  "page": "https://commons.wikimedia.org/wiki/File:Biotite_aggregate_-_Ochtendung,_Eifel,_Germany.jpg"
 },
 "Serpentine": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/3/34/SerpentineUSGOV.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "Public domain",
  "credit": "Unknown authorUnknown author",
  "page": "https://commons.wikimedia.org/wiki/File:SerpentineUSGOV.jpg"
 },
 "Celestine": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Celestine_-_Sakoany_deposit%2C_Katsepy%2C_Mitsinjo%2C_Boeny%2C_Madagascar.jpg/500px-Celestine_-_Sakoany_deposit%2C_Katsepy%2C_Mitsinjo%2C_Boeny%2C_Madagascar.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 4.0",
  "credit": "Ivar Leidus",
  "page": "https://commons.wikimedia.org/wiki/File:Celestine_-_Sakoany_deposit,_Katsepy,_Mitsinjo,_Boeny,_Madagascar.jpg"
 },
 "Antigorite (Serpentine)": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Antigorite-199680.jpg/500px-Antigorite-199680.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Antigorite-199680.jpg"
 },
 "Almandine Garnet": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/4/44/Almandine-131923.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
  "license": "CC BY-SA 3.0",
  "credit": "Robert M. Lavinsky",
  "page": "https://commons.wikimedia.org/wiki/File:Almandine-131923.jpg"
 },
 "Conglomerate": {
  "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Ferruginous_quartz-pebble_conglomerate_%28derived_from_boulder_in_%22Sharon_Conglomerate%22%2C_Lower_Pennsylvanian%3B_Jackson_North_roadcut%2C_Ohio%2C_USA%29_30.jpg/500px-Ferruginous_quartz-pebble_conglomerate_%28derived_from_boulder_in_%22Sharon_Conglomerate%22%2C_Lower_Pennsylvanian%3B_Jackson_North_roadcut%2C_Ohio%2C_USA%29_30.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "license": "CC BY 2.0",
  "credit": "James St. John",
  "page": "https://commons.wikimedia.org/wiki/File:Ferruginous_quartz-pebble_conglomerate_(derived_from_boulder_in_%22Sharon_Conglomerate%22,_Lower_Pennsylvanian;_Jackson_North_roadcut,_Ohio,_USA)_30.jpg"
 }
};
